apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heartbeat.fullname" . }}-heartbeat
  labels:
    k8s-app: heartbeat
  {{- include "heartbeat.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      k8s-app: heartbeat
    {{- include "heartbeat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        k8s-app: heartbeat
      {{- include "heartbeat.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args: {{- toYaml .Values.heartbeat.heartbeat.args | nindent 8 }}
        env:
        - name: ELASTICSEARCH_HOST
          value: {{ quote .Values.heartbeat.heartbeat.env.elasticsearchHost }}
        - name: ELASTICSEARCH_PORT
          value: {{ quote .Values.heartbeat.heartbeat.env.elasticsearchPort }}
        - name: ELASTICSEARCH_USERNAME
          value: {{ quote .Values.heartbeat.heartbeat.env.elasticsearchUsername }}
        - name: ELASTICSEARCH_PASSWORD
          value: {{ quote .Values.heartbeat.heartbeat.env.elasticsearchPassword }}
        - name: ELASTIC_CLOUD_ID
          value: {{ quote .Values.heartbeat.heartbeat.env.elasticCloudId }}
        - name: ELASTIC_CLOUD_AUTH
          value: {{ quote .Values.heartbeat.heartbeat.env.elasticCloudAuth }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.heartbeat.heartbeat.image.repository }}:{{ .Values.heartbeat.heartbeat.image.tag
          | default .Chart.AppVersion }}
        name: heartbeat
        resources: {{- toYaml .Values.heartbeat.heartbeat.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.heartbeat.heartbeat.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /etc/heartbeat.yml
          name: config
          readOnly: true
          subPath: heartbeat.yml
        - mountPath: /usr/share/heartbeat/data
          name: data
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      serviceAccountName: {{ include "heartbeat.fullname" . }}-heartbeat
      volumes:
      - configMap:
          defaultMode: 384
          name: {{ include "heartbeat.fullname" . }}-deployment-config
        name: config
      - hostPath:
          path: /var/lib/heartbeat-data
          type: DirectoryOrCreate
        name: data