apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "heartbeat.fullname" . }}-deployment-config
  labels:
    k8s-app: heartbeat
  {{- include "heartbeat.labels" . | nindent 4 }}
data:
  heartbeat.yml: {{ .Values.deploymentConfig.heartbeatYml | toYaml | indent 1 }}