apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "heartbeat.fullname" . }}-heartbeat
  labels:
    k8s-app: heartbeat
  {{- include "heartbeat.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "heartbeat.fullname" . }}-heartbeat
  labels:
    k8s-app: heartbeat
  {{- include "heartbeat.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "heartbeat.fullname" . }}-heartbeat
  labels:
  {{- include "heartbeat.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "heartbeat.fullname" . }}-heartbeat'
subjects:
- kind: ServiceAccount
  name: '{{ include "heartbeat.fullname" . }}-heartbeat'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "heartbeat.fullname" . }}-heartbeat
  labels:
  {{- include "heartbeat.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "heartbeat.fullname" . }}-heartbeat'
subjects:
- kind: ServiceAccount
  name: '{{ include "heartbeat.fullname" . }}-heartbeat'
  namespace: '{{ .Release.Namespace }}'