apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "heartbeat.fullname" . }}-kubeadm-config
  labels:
    k8s-app: heartbeat
  {{- include "heartbeat.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubeadm-config
  resources:
  - configmaps
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "heartbeat.fullname" . }}-kubeadm-config
  labels:
  {{- include "heartbeat.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "heartbeat.fullname" . }}-kubeadm-config'
subjects:
- kind: ServiceAccount
  name: '{{ include "heartbeat.fullname" . }}-heartbeat'
  namespace: '{{ .Release.Namespace }}'