apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "heartbeat.fullname" . }}-heartbeat
  labels:
    k8s-app: heartbeat
  {{- include "heartbeat.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.heartbeat.serviceAccount.annotations | nindent 4 }}