heartbeat.monitors:
  - type: http
    schedule: '@every 5s'
    urls:
      - http://elasticsearch-master:9200
      - http://kibana:5601

  - type: icmp
    schedule: '@every 5s'
    hosts:
      - elasticsearch-master
      - kibana

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: 'elasticsearch-master:9200'
  username: 'heartbeat_write'
  password: 'Hujan404'
