deploymentConfig:
  heartbeatYml: |-
    #heartbeat.autodiscover: # Enable one or more of the providers below
    #  providers:
    #    - type: kubernetes
    #      resource: pod
    #      scope: cluster
    #      node: ${NODE_NAME}
    #      hints.enabled: true
    #
    #    - type: kubernetes
    #      resource: service
    #      scope: cluster
    #      node: ${NODE_NAME}
    #      hints.enabled: true
    #
    #    - type: kubernetes
    #      resource: node
    #      node: ${NODE_NAME}
    #      scope: cluster
    #      templates:
    #        # Example, check SSH port of all cluster nodes:
    #        - condition: ~
    #          config:
    #            - hosts:
    #                - ${data.host}:22
    #              name: ${data.kubernetes.node.name}
    #              schedule: '@every 10s'
    #              timeout: 5s
    #              type: tcp
    processors:
      - add_cloud_metadata:
    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
heartbeat:
  heartbeat:
    args:
      - -c
      - /etc/heartbeat.yml
      - -e
    containerSecurityContext:
      runAsUser: 0
    env:
      elasticCloudAuth: ''
      elasticCloudId: ''
      elasticsearchHost: elasticsearch
      elasticsearchPassword: changeme
      elasticsearchPort: '9200'
      elasticsearchUsername: elastic
    image:
      repository: docker.elastic.co/beats/heartbeat
      tag: 8.8.1
    resources:
      limits:
        memory: 1536Mi
      requests:
        cpu: '2'
        memory: 1536Mi
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
